### PR TITLE
Added multiple commands input

### PR DESCRIPTION
**Pull request by cristianku**
Now its possible to send multiple commands separated by ; 

For example OT2;50;OT1;100

### CODE REVIEW

**Comment by cristianku** [comment]
Now its possible to send multiple commands separated by ;

For example OT2;50;OT1;100

**Comment by mgmcderm** [comment]
Thanks. Dummy question. How do I implement this change?

**Comment by Krullus** [comment]
There have been many changes, and I find it difficult to keep track of them. Why is everything marked with a C?
Additionally, there are new changes that seem to require more hardware for e.g. BT and ET measurement?
maybe that should be in another sketch? I will try to find original pull request for multiple commands. must be this alone [ad528bb](https://github.com/jmoore52/SkywalkerRoaster/pull/16/commits/ad528bbdd1a86e9e4fbdd5146f444259d32bad72)?

**Comment by Krullus** [comment]
I created a new branch from your commits and resolved the pull request.

Your original pull request has been resolved, and now it's possible to send multiple commands separated by a semicolon ;

For example: OT2;50;OT1;100.

Closing this pull request now

**Pull request closed without merging**
